name: Build
on: [ push ]
jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "linux", "darwin", "windows" ]
        arch: [ "amd64", "arm64" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
      - name: Build Executable
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} -ldflags="-s -w" -v .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          path: portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
      - name: Create and publish release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          automatic_release_tag: "new"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Downloads"
          files: |
            portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          prerelease: false